var backdrop = localStorage.getItem("backdrop");
var title = localStorage.getItem("title")
var runtime  = localStorage.getItem("runtime")
var releaseDate = localStorage.getItem("releaseDate")
var video = localStorage.getItem("video")

var castName0 = localStorage.getItem("castName0")
var castName1 = localStorage.getItem("castName1")
var castName2 = localStorage.getItem("castName2")
var castName3 = localStorage.getItem("castName3")
var castName4 = localStorage.getItem("castName4")
var castName5 = localStorage.getItem("castName5")
var castName6 = localStorage.getItem("castName6")
var castName7 = localStorage.getItem("castName7")
var castName8 = localStorage.getItem("castName8")
var castName9 = localStorage.getItem("castName9")

var castPath0 = localStorage.getItem("castPath0")
var castPath1 = localStorage.getItem("castPath1")
var castPath2 = localStorage.getItem("castPath2")
var castPath3 = localStorage.getItem("castPath3")
var castPath4 = localStorage.getItem("castPath4")
var castPath5 = localStorage.getItem("castPath5")
var castPath6 = localStorage.getItem("castPath6")
var castPath7 = localStorage.getItem("castPath7")
var castPath8 = localStorage.getItem("castPath8")
var castPath9 = localStorage.getItem("castPath9")

var genre0 = localStorage.getItem('genre0')
var genre1 = localStorage.getItem("genre1")
var genre2 = localStorage.getItem('genre2')
var genre3 = localStorage.getItem('genre3')

localStorage.clear()

console.log(backdrop,title,runtime,releaseDate,video,castName7,genre0)